# Generated by Django 4.1.2 on 2022-11-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_birthday_year_book_biography_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='biography',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='user',
        ),
    ]
